ETH and Token Streaming Challenge
BuidlGuidl/eth-tech-tree-challenges-old pull request #19
Opened 2024-05-21 18:50 UTC by MattPereira

Fixes #4 

## Summary
Still a WIP draft 

## Resources
- https://vscode.blockscan.com/ethereum/0x2634aF3E799D3E17C6cf30bCF1275A7e3808F0df
- https://vscode.blockscan.com/ethereum/0x518Af5F20bf07C882e17731207761C174AB4F9c4

2024-05-28 18:35 UTC, escottalexander requested changes
Great work! This is looking really good. Just a few suggestions and questions for you.

2024-05-28 18:35 UTC, escottalexander commented on README.md
> +In a world where asset allocation mechanisms have grown stale, a visionary group of technologists known as **_The StreamWeavers_** emerges. Their mission is to pioneer novel means of distributing cap
💯

2024-05-28 18:35 UTC, escottalexander commented on README.md
> +Amidst a backdrop where centralized control over capital resouces stifles innovation and freedom, your challenge is to write a smart contract named "EthStreaming". This contract will empower authoriz
...since their last *withdrawal*. <- typo

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +import {console} from "forge-std/console.sol";
We have been including console2 because I think it's better. Let me know if I am wrong about this.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +    error InsufficentFunds();
Good call to write custom errors. We probably should have been doing that for everything up to this point.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +        StreamConfig storage builderStream = s_streamRegistry[account];
explain your naming scheme to me here: s_streamRegistry. What does the s mean?
I am assuming i_frequency is i == immutable. s == secret (private)?

Also make a case for the lowercase snake case + camel case. We have been using uppercase snake case in the tests for defining state variables but otherwise are using camel case.

My "feel" on this would be using upper case snake case for an immutable state variable (like i_frequency) but just using camel case for anything else. Feel free to reference any good reads on why you think differently.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +     * - Revert if the sender does not have a stream
Add the requirement to emit the Withdraw event.

Also should mention reverting if the transfer is unsuccessful.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +        StreamConfig storage builderStream = s_streamRegistry[account];
I am feeling like we should be consistent throughout all the challenges. I would advise renaming s_streamingRegistry to streamRegistry and i_frequency to FREQUENCY. Still curious to hear if you think your naming scheme is better practice.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +
Remove this extra line. Comparing to above where you designate the external functions section.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +    function maxWithdraw() public hasStream(msg.sender) {
Love how you are using this modifier throughout.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +     * @param account account to get stream for
We should also have a `@return` NatSpec comment here.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +     * @dev This is a special fallback function allows the contract to receive ether 👉 https://solidity-by-example.org/fallback/
"This is a special fallback function *which* allows..." or "This ~~is a~~ special fallback..."

Glad you added the Solidity By Example reference here.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/test/EthStreaming.sol
> +     * @notice Alice is given a stream, but Bob has no stream to start
Love that you added comments to the test. That will probably be very helpful when a user is trying to debug.

2024-05-28 18:35 UTC, escottalexander commented on packages/foundry/test/EthStreaming.sol
> +     * @notice TODO WIP
Did you mean to leave this as TODO?

2024-05-28 21:58 UTC, MattPereira commented on packages/foundry/contracts/EthStreaming.sol
> +import {console} from "forge-std/console.sol";
`console2` is definitely better nice catch

2024-05-28 22:07 UTC, MattPereira commented on packages/foundry/contracts/EthStreaming.sol
> +        StreamConfig storage builderStream = s_streamRegistry[account];
I fully agree styles should be consistent throughout the challenges. I meant to bring up discussion about what the conventions should be using my funky styles as an example :rofl: 

i learned the `s_` and `i_` convention from Patrick Collins advanced foundry course. `s_` is for state variables which allows you to use a matching var name minus the `s_` as a param for a function instead of doing the `_param` thing.  It also helps you remember what is a state variable and what is not when things get intense with longer contracts. Here is example contract from the course with all of his favored techniques

https://github.com/Cyfrin/foundry-defi-stablecoin-f23/blob/main/src/DSCEngine.sol

2024-05-28 22:13 UTC, MattPereira commented on packages/foundry/contracts/EthStreaming.sol
> +        StreamConfig storage builderStream = s_streamRegistry[account];
That said I'm down for using whatever style conventions. It all just depends on how particular we want to be.

Do we want to definite a specific layout order similar to Patrick's? 
 
 ```
 // Layout of Contract:
// version
// imports
// errors
// interfaces, libraries, contracts
// Type declarations
// State variables
// Events
// Modifiers
// Functions

// Layout of Functions:
// constructor
// receive function (if exists)
// fallback function (if exists)
// external
// public
// internal
// private
// internal & private view & pure functions
// external & public view & pure functions
 ```

Do we want to do the big layout section comment dividers? 
```
    ///////////////////
    // Public Functions
    ///////////////////
```

I definitely like the convention you came up with for the natspec where its like
```
     * Requirements:
     * - Only owner can add a stream
```

2024-05-29 14:32 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +        StreamConfig storage builderStream = s_streamRegistry[account];
I like that layout. I will start to use it and enforce it on code reviews. Big layout dividers are very clear so I like that.

2024-05-29 14:44 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +        StreamConfig storage builderStream = s_streamRegistry[account];
> I fully agree styles should be consistent throughout the challenges. I meant to bring up discussion about what the conventions should be using my funky styles as an example 🤣
> 
> i learned the `s_` and `i_` convention from Patrick Collins advanced foundry course. `s_` is for state variables which allows you to use a matching var name minus the `s_` as a param for a function instead of doing the `_param` thing. It also helps you remember what is a state variable and what is not when things get intense with longer contracts. Here is example contract from the course with all of his favored techniques
> 
> https://github.com/Cyfrin/foundry-defi-stablecoin-f23/blob/main/src/DSCEngine.sol

Thanks for sharing that. The reasoning makes sense but I feel like we would need to teach challengers the ins and outs of that style choice for them to be able to make use of it. I feel like it makes things more confusing upfront even though long term it may be better. Up to this point SRE challenges are not very strict on styles so I am not sure where to draw the line. Let's just match the existing styles of challenges and try maintain that throughout.

2024-05-29 21:22 UTC, escottalexander requested changes
Looking good. Would like to see frequency changed to FREQUENCY.

2024-05-29 21:22 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +    uint256 public immutable frequency = 2592000; // How long until stream is fully unlocked after last withdrawal
I would make this `FREQUENCY`

2024-05-29 21:24 UTC, escottalexander commented
> * Based on [answers to my previous questions](https://github.com/BuidlGuidl/eth-tech-tree-challenges/issues/10#issuecomment-2120790694), my suggestion is to simplify the challenge to be only ETH streaming for level 1 and maybe consider adding a level 2 challenge that involves partial withdraws and allows for streams of any

This is a great idea to make a level 2 challenge that adds all those features. I'll add an issue for it so I don't lose your idea.

2024-05-30 14:08 UTC, escottalexander requested changes
Another thing I noticed.

2024-05-30 14:08 UTC, escottalexander commented on packages/foundry/test/EthStreaming.sol
> +        vm.expectRevert("Ownable: caller is not the owner");
This should be a custom error. Need to add wording to the requirements for this as well.

2024-05-30 18:27 UTC, swellander commented on README.md
> +In a world where asset allocation mechanisms have grown stale, a visionary group of technologists known as **_The StreamWeavers_** emerges. Their mission is to pioneer novel means of distributing cap
:fire:

2024-05-31 19:36 UTC, MattPereira commented on packages/foundry/test/EthStreaming.sol
> +        vm.expectRevert("Ownable: caller is not the owner");
Hmm can you help me understand how I should go about setting up a custom error for this?

the revert is triggered by the `onlyOwner` modifier from Openzeppelin's `Ownable` contract shown below

![image](https://github.com/BuidlGuidl/eth-tech-tree-challenges/assets/73561520/5221c295-a89d-4c33-a597-26c70470da0e)

Are you wanting me to not use Openzeppelin for this and instead just mimic the logic? my thought was it'd be good to get new dev used to navigating imports and reading the code from inhereted contracts so i've modified the natspec as a suggestion, but happy to take this in whatever direction you prefer


![image](https://github.com/BuidlGuidl/eth-tech-tree-challenges/assets/73561520/9ef98635-8978-49e1-95df-a0c470ee8393)

2024-05-31 20:27 UTC, escottalexander commented on packages/foundry/test/EthStreaming.sol
> +        vm.expectRevert("Ownable: caller is not the owner");
No, you are correct. I mistakenly thought it was a non-custom error you had written into your contract. Sorry for the misdirection.

2024-05-31 20:29 UTC, escottalexander commented on packages/foundry/contracts/EthStreaming.sol
> +     * - Use a modifier inhereted from OpenZeppelin's Ownable contract to prevent accounts that are not the owner of this contract from adding streams
~~inhereted~~ inherited

2024-05-31 20:44 UTC, escottalexander approved these changes
Nice work. This is good to go!

2024-05-31 20:44 UTC, merged