Dead mans switch
BuidlGuidl/eth-tech-tree-challenges-old pull request #29
Opened 2024-05-25 05:13 UTC by KcPele

## Description
Added challenge smart contract, test and description 
_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

2024-05-26 11:37 UTC, escottalexander requested changes
Great job pulling this together! Left some suggestions for you. This is really close.

2024-05-26 11:37 UTC, escottalexander commented on README.md
>  # Template For Challenge - ETH Tech Tree
~~Template For Challenge~~ Replace with: Dead Man's Switch

2024-05-26 11:37 UTC, escottalexander commented on README.md
> +_End of challenge specific section_
Remove this line. It was just there to help you know where to edit.

2024-05-26 11:37 UTC, escottalexander commented on README.md
>  Here are some helpful references:
If you don't have any helpful resource links then remove this section.

2024-05-26 11:37 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    function testWithdraw() public {
This test is failing. There are two solutions. It is failing because when it tries to move the ether the testing contract doesn't have these methods:
``` solidity
    receive() external payable {}
    fallback() external payable {}
``` 
Without those methods attempts to send ether to a contract will fail. An alternative to adding those methods would be to use a EOA account that is not a contract. That would require adding these two lines to the top of the test so that it runs the test as another account that is not a contract.
```solidity
    vm.deal(NON_CONTRACT_USER, ONE_THOUSAND);
    vm.startPrank(NON_CONTRACT_USER);
```

2024-05-26 11:37 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +        for (uint i = 0; i < user.beneficiaries.length; i++) {
For loops are strongly discouraged in Solidity because they lead to [issues](https://stackoverflow.com/questions/48113615/solidity-for-loop-over-a-huge-amount-of-data), just one example. When it is possible we should try to avoid them.

Lucky for us we can replace the beneficiaries array with a isBeneficiary mapping(address => bool) in the Users struct. Then all you need to do here is check if `user.isBeneficiary[beneficiary] == false`.

Then you can set them to true instead of adding to an array: user.isBeneficiary[beneficiary] = true;

2024-05-26 11:37 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +        for (uint i = 0; i < user.beneficiaries.length; i++) {
Here too we can avoid the for loop by utilizing the mapping:
```solidity
      require(user.isBeneficiary[msg.sender], "Caller is not a beneficiary");
```

2024-05-26 11:37 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +    function getBeneficiaries(
Since we are using a mapping now, this method will need to be changed to a helper method for getting the values of the mapping from the struct.
Something like this.
```solidity
function getUserBeneficiary(address userAddress, address beneficiary) public view returns (bool) {
      users[userAddress].isBeneficiary[beneficiary];
}
```
Make sure you update the NatSpec as well so that the user knows what to do.

2024-05-26 11:37 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    function testAddBeneficiary() public {
You will need to update this test to use the new view method for isBeneficiary instead of the array.

2024-05-26 11:37 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +}
This also means it becomes negligible to add a removeBeneficiary method since all we have to do is set the value in the mapping to false. Let's add that in this file and don't forget some tests too.

2024-05-26 11:37 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +}
Don't forget tests for the new removeBeneficiary method I mentioned.

2024-05-27 15:55 UTC, escottalexander requested changes
Hey KC, A few more changes suggested. Nice work implementing the new mapping. Looking great!

Feel free to reach out on Telegram if you have questions about my comments.

2024-05-27 15:55 UTC, escottalexander commented on README.md
> +# Dead Man's Switch
Oh sorry, I should have been clearer. Can you change this to "Dead Man's Switch - ETH Tech Tree". This way it will match the other challenges.

2024-05-27 15:55 UTC, escottalexander commented on README.md
> -##### Scenario:
Sorry again, KC. I meant to say you should remove the "Here are some helpful references: ..." section. You can add your scenario section back in. I liked it. 

The references section was just meant to be an example of where/how you could include some links to articles or other materials related to this challenge. If you don't know of any then you can remove the section.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +        mapping(address => bool) beneficiaries;
Could we change the name of this to "isBeneficiary" or "beneficiaryLookup"? Because it is more of a lookup to see if a specific address is a beneficiary. I think that reads better when you are looking at where it is used and it helps the user understand it's purpose.

As it is right now, there is no way to return all beneficiaries from it and I feel like that is what it communicates if it is called beneficiaries.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +     * @return The check-in interval of the user.
Need to add requirements so the challenger knows what it needs to do.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +    fallback() external payable {}
These methods are not needed so I would remove them. When I mentioned them in the last review I was trying to say that they would need to be added to the testing contract "DeadMansSwitch.t.sol" but only if you didn't add the NON_CONTRACT_USER deal and startPranks. Looks like you did so you should be good. Just remove them from here.

The risk in adding receive and fallback here is that it allows a user to deposit to the contract without the contract updating their specific balance. leading to funds stuck in the contract.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
>      // // Test withdrawing funds by the user
Remove the extra set of "//".

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +        vm.expectRevert("Caller is not a beneficiary");
Change this line to `vm.expectRevert();`

Because we don't know what revert message to expect but we do know we want to it to revert in some way.

That way no matter what revert message the user chooses for this condition the test will still pass.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +        vm.expectRevert("Check-in interval has not passed");
Change this line to `vm.expectRevert();`

Because we don't know what revert message to expect but we do know we want to it to revert in some way.

That way no matter what revert message the user chooses for this condition the test will still pass.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    function testWithdrawAsNonBeneficiary() public {
Let's add another version of this test where a non-beneficiary tries to withdraw before the interval. It will be good to have that edge case covered just in case the challenger's logic has a hole.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    uint ONE_THOUSAND = 10 wei;
Shouldn't ONE_THOUSAND be 1000 wei?

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    // Test removing a beneficiary
Add new line above to separate these properly.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +        assertEq(deadMansSwitch.getBalance(THIS_CONTRACT), 0);
Add an assertion that the beneficiaries balance was updated to the amount expected.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +     * - Emits a `BeneficiaryRemoved` event with the caller's address and the beneficiary address.
Add a requirement that "The beneficiary is removed". Hopefully it is obvious to them but no harm in adding clarity.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +    }
Let's remove these methods completely. We can get the values of these in the tests with 
`(uint balance, uint lastCheckIn, uint checkInInterval) = deadmansswitch.users[ADDRESS];`
Or if you only need one of them you can do this:
```
(uint balance,,) = deadmansswitch.users[ADDRESS];
(,uint lastCheckIn,) = deadmansswitch.users[ADDRESS];
(,,uint checkInInterval) = deadmansswitch.users[ADDRESS];
```

Just no reason to require a user to build them if they aren't needed.

2024-05-27 15:55 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    }
Because we are requiring that the beneficiary is not the zero address and that they can't already be a beneficiary, we should add tests to check that those cases are true.

2024-05-27 15:59 UTC, KcPele commented
Great

On Mon, 27 May 2024, 16:55 escottalexander, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey KC, A few more changes suggested. Nice work implementing the new
> mapping. Looking great!
>
> Feel free to reach out on Telegram if you have questions about my comments.
> ------------------------------
>
> In README.md
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616059170>
> :
>
> > @@ -1,4 +1,4 @@
> -# Template For Challenge - ETH Tech Tree
> +# Dead Man's Switch
>
> Oh sorry, I should have been clearer. Can you change this to "Dead Man's
> Switch - ETH Tech Tree". This way it will match the other challenges.
> ------------------------------
>
> In README.md
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616064468>
> :
>
> > @@ -30,18 +30,12 @@ foundryup
>
>  In this challenge, you will create a smart contract that implements a "Dead Man's Switch". This contract allows users to deposit funds (ETH or other tokens) and set a time interval for regular "check-ins". If the user fails to check in within the specified time frame, designated beneficiaries can withdraw the funds.
>
> -##### Scenario:
>
> Sorry again, KC. I meant to say you should remove the "Here are some
> helpful references: ..." section. You can add your scenario section back
> in. I liked it.
>
> The references section was just meant to be an example of where/how you
> could include some links to articles or other materials related to this
> challenge. If you don't know of any then you can remove the section.
> ------------------------------
>
> In packages/foundry/contracts/DeadMansSwitch.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616085971>
> :
>
> >
>      // Struct to store user data
>      struct User {
>          uint balance;
>          uint lastCheckIn;
>          uint checkInInterval;
> -        address[] beneficiaries;
> +        mapping(address => bool) beneficiaries;
>
> Could we change the name of this to "isBeneficiary" or
> "beneficiaryLookup"? Because it is more of a lookup to see if a specific
> address is a beneficiary. I think that reads better when you are looking at
> where it is used and it helps the user understand it's purpose.
>
> As it is right now, there is no way to return all beneficiaries from it
> and I feel like that is what it communicates if it is called beneficiaries.
> ------------------------------
>
> In packages/foundry/contracts/DeadMansSwitch.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616089705>
> :
>
> >       * @param userAddress The address of the user.
> -     * @return The beneficiaries of the user.
> +     * @param beneficiary The address of the beneficiary.
> +     * @return The check-in interval of the user.
>
> Need to add requirements so the challenger knows what it needs to do.
> ------------------------------
>
> In packages/foundry/contracts/DeadMansSwitch.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616093946>
> :
>
> >      }
> +
> +    receive() external payable {}
> +    fallback() external payable {}
>
> These methods are not needed so I would remove them. When I mentioned them
> in the last review I was trying to say that they would need to be added to
> the testing contract "DeadMansSwitch.t.sol" but only if you didn't add the
> NON_CONTRACT_USER deal and startPranks. Looks like you did so you should be
> good. Just remove them from here.
>
> The risk in adding receive and fallback here is that it allows a user to
> deposit to the contract without the contract updating their specific
> balance. leading to funds stuck in the contract.
> ------------------------------
>
> In packages/foundry/test/DeadMansSwitchTest.t.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616102086>
> :
>
> >          );
> -        assertEq(beneficiaries.length, 1);
> -        assertEq(beneficiaries[0], BENEFICIARY_1);
>      }
>
>      // // Test withdrawing funds by the user
>
> Remove the extra set of "//".
> ------------------------------
>
> In packages/foundry/test/DeadMansSwitchTest.t.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616113682>
> :
>
> > +        deadMansSwitch.deposit{value: ONE_THOUSAND}();
> +        deadMansSwitch.setCheckInInterval(INTERVAL);
> +        deadMansSwitch.addBeneficiary(BENEFICIARY_1);
> +        vm.warp(block.timestamp + INTERVAL + 1);
> +        vm.startPrank(BENEFICIARY_1);
> +        deadMansSwitch.withdrawAsBeneficiary(THIS_CONTRACT);
> +        assertEq(deadMansSwitch.getBalance(THIS_CONTRACT), 0);
> +    }
> +
> +    // Test that non-beneficiaries cannot withdraw funds
> +    function testWithdrawAsNonBeneficiary() public {
> +        deadMansSwitch.deposit{value: ONE_THOUSAND}();
> +        deadMansSwitch.setCheckInInterval(INTERVAL);
> +        vm.warp(block.timestamp + INTERVAL + 1);
> +        vm.startPrank(NON_CONTRACT_USER);
> +        vm.expectRevert("Caller is not a beneficiary");
>
> Change this line to vm.expectRevert();
>
> Because we don't know what revert message to expect but we do know we want
> to it to revert in some way.
>
> That way no matter what revert message the user chooses for this condition
> the test will still pass.
> ------------------------------
>
> In packages/foundry/test/DeadMansSwitchTest.t.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616113819>
> :
>
> > +        deadMansSwitch.deposit{value: ONE_THOUSAND}();
> +        deadMansSwitch.setCheckInInterval(INTERVAL);
> +        vm.warp(block.timestamp + INTERVAL + 1);
> +        vm.startPrank(NON_CONTRACT_USER);
> +        vm.expectRevert("Caller is not a beneficiary");
> +        deadMansSwitch.withdrawAsBeneficiary(THIS_CONTRACT);
> +    }
> +
> +    // Test that beneficiaries cannot withdraw funds before the interval has passed
> +    function testWithdrawAsBeneficiaryBeforeInterval() public {
> +        deadMansSwitch.deposit{value: ONE_THOUSAND}();
> +        deadMansSwitch.setCheckInInterval(INTERVAL);
> +        deadMansSwitch.addBeneficiary(BENEFICIARY_1);
> +        vm.warp(block.timestamp + INTERVAL - 1);
> +        vm.startPrank(BENEFICIARY_1);
> +        vm.expectRevert("Check-in interval has not passed");
>
> Change this line to vm.expectRevert();
>
> Because we don't know what revert message to expect but we do know we want
> to it to revert in some way.
>
> That way no matter what revert message the user chooses for this condition
> the test will still pass.
> ------------------------------
>
> In packages/foundry/test/DeadMansSwitchTest.t.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616116720>
> :
>
> > +        assertEq(deadMansSwitch.getBalance(THIS_CONTRACT), 0);
> +    }
> +
> +    // Test withdrawing funds by a beneficiary after the interval has passed
> +    function testWithdrawAsBeneficiary() public {
> +        deadMansSwitch.deposit{value: ONE_THOUSAND}();
> +        deadMansSwitch.setCheckInInterval(INTERVAL);
> +        deadMansSwitch.addBeneficiary(BENEFICIARY_1);
> +        vm.warp(block.timestamp + INTERVAL + 1);
> +        vm.startPrank(BENEFICIARY_1);
> +        deadMansSwitch.withdrawAsBeneficiary(THIS_CONTRACT);
> +        assertEq(deadMansSwitch.getBalance(THIS_CONTRACT), 0);
> +    }
> +
> +    // Test that non-beneficiaries cannot withdraw funds
> +    function testWithdrawAsNonBeneficiary() public {
>
> Let's add another version of this test where a non-beneficiary tries to
> withdraw before the interval. It will be good to have that edge case
> covered just in case the challenger's logic has a hole.
> ------------------------------
>
> In packages/foundry/test/DeadMansSwitchTest.t.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1616164528>
> :
>
> > @@ -0,0 +1,148 @@
> +// SPDX-License-Identi [...]

2024-05-27 16:04 UTC, KcPele commented on README.md
> -##### Scenario:
ok

2024-05-27 17:04 UTC, KcPele commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    uint ONE_THOUSAND = 10 wei;
my bad

2024-05-28 11:59 UTC, escottalexander requested changes
Looking great! Nice work. Just a few small nit picks.

2024-05-28 11:59 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +     * @dev Allows isBeneficiary to withdraw the user's funds if the check-in interval has passed.
I think this was accidentally changed and should remain "beneficiaries"

2024-05-28 11:59 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +     * - The caller must be one of the user's isBeneficiary.
Same here. Should be "beneficiaries"

2024-05-28 11:59 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
>       * @param beneficiary The address of the beneficiary.
Should add "@return boolean representing whether the address is a beneficiary"

2024-05-28 11:59 UTC, escottalexander commented on packages/foundry/contracts/DeadMansSwitch.sol
> +     * - The beneficiary must be added.
I would change this to "returns true or false if the provided beneficiary is a given userAddresses beneficiary"

2024-05-28 11:59 UTC, escottalexander commented on packages/foundry/test/DeadMansSwitchTest.t.sol
> +    // Test that non-beneficiaries cannot withdraw funds before the interval has passed
Add extra line above this so that spacing is the same throughout.

2024-05-28 12:30 UTC, KcPele commented
Thanks for the feedback!

On Tue, 28 May 2024, 13:00 escottalexander, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Looking great! Nice work. Just a few small nit picks.
> ------------------------------
>
> In packages/foundry/contracts/DeadMansSwitch.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1617103436>
> :
>
> > @@ -109,10 +110,10 @@ contract DeadMansSwitch {
>      }
>
>      /**
> -     * @dev Allows beneficiaries to withdraw the user's funds if the check-in interval has passed.
> +     * @dev Allows isBeneficiary to withdraw the user's funds if the check-in interval has passed.
>
> I think this was accidentally changed and should remain "beneficiaries"
> ------------------------------
>
> In packages/foundry/contracts/DeadMansSwitch.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1617104032>
> :
>
> >       * @param userAddress The address of the user.
>       * Requirements:
> -     * - The caller must be one of the user's beneficiaries.
> +     * - The caller must be one of the user's isBeneficiary.
>
> Same here. Should be "beneficiaries"
> ------------------------------
>
> In packages/foundry/contracts/DeadMansSwitch.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1617110522>
> :
>
> > -     */
> -    function getLastCheckIn(address userAddress) public view returns (uint) {
> -        return users[userAddress].lastCheckIn;
> -    }
> -
> -    /**
> -     * @dev Gets the check-in interval of the user.
> -     * @param userAddress The address of the user.
> -     * @return The check-in interval of the user.
> -     */
> -    function getCheckInInterval(
> -        address userAddress
> -    ) public view returns (uint) {
> -        return users[userAddress].checkInInterval;
> -    }
> -
>      /**
>       * @dev Gets to check if there is a beneficiary.
>       * @param userAddress The address of the user.
>       * @param beneficiary The address of the beneficiary.
>
> Should add ***@***.*** <https://github.com/return> boolean representing
> whether the address is a beneficiary"
> ------------------------------
>
> In packages/foundry/contracts/DeadMansSwitch.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1617110907>
> :
>
> >      /**
>       * @dev Gets to check if there is a beneficiary.
>       * @param userAddress The address of the user.
>       * @param beneficiary The address of the beneficiary.
> -     * @return The check-in interval of the user.
> +     * Requirements:
> +     * - The beneficiary must be added.
>
> I would change this to "returns true or false if the provided beneficiary
> is a given userAddresses beneficiary"
> ------------------------------
>
> In packages/foundry/test/DeadMansSwitchTest.t.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#discussion_r1617114022>
> :
>
> > @@ -85,7 +98,16 @@ contract DeadMansSwitchTest is Test {
>          deadMansSwitch.setCheckInInterval(INTERVAL);
>          vm.warp(block.timestamp + INTERVAL + 1);
>          vm.startPrank(NON_CONTRACT_USER);
> -        vm.expectRevert("Caller is not a beneficiary");
> +        vm.expectRevert();
> +        deadMansSwitch.withdrawAsBeneficiary(THIS_CONTRACT);
> +    }
> +    // Test that non-beneficiaries cannot withdraw funds before the interval has passed
>
> Add extra line above this so that spacing is the same throughout.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/29#pullrequestreview-2082564984>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APJDTO63BBY2P5TEENFF62LZERWVBAVCNFSM6AAAAABIIS4KBCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOBSGU3DIOJYGQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***
> com>
>

2024-05-28 18:43 UTC, escottalexander approved these changes
Nice work! Everything looks good.

2024-05-28 18:43 UTC, merged

2024-05-29 11:49 UTC, escottalexander commented
Closed #22