Write initial Multisend.sol educational challenge & tests
BuidlGuidl/eth-tech-tree-challenges-old pull request #31
Opened 2024-05-29 04:19 UTC by steve0xp

## Description

Create Multisend challenge as per issue #3.

## TODO

- [x] Create initial `Multisend.sol`
- [x] Create initial `Multisend.t.sol` tests (pseudo-code)
- [ ] Debug tests and contract to ensure challenge works
- [ ] Write README sections

## Additional Information

Some assumptions were made when starting this PR:
- It's okay that address array params have repeating addresses (perhaps the use case was someone pasting in addresses into the params and they didn't bother to combine repeat addresses with corresponding amounts in the amounts array)
- `sendTokens()` to only carry out the transference of one `ERC20` token at a time, aka not to do a variety of **different** ERC20 transfers within the single function call.

## Related Issues

_Closes #3_

Your ENS/address: steve0xp.eth

2024-05-29 14:33 UTC, steve0xp commented
Current status:
- Bug occurring on the transference of tokens and ETH. So there probably is something wrong with the actual implementation in `Multisend.sol`. Sadly don't have time to debug today, but can get to it in the coming days.

2024-05-29 16:30 UTC, escottalexander commented on packages/foundry/test/Multisend.t.sol
> +        multisend.sendETH(recipients, amounts);
Need to include the value you are sending in the call.
```solidity
multisend.sendETH{value: amounts[0] + amounts[1] }(recipients, amounts);
```

2024-05-29 18:11 UTC, steve0xp commented on packages/foundry/test/Multisend.t.sol
> +        multisend.sendETH(recipients, amounts);
Good catch, yep added this in my most recent commit. Thanks mate!

2024-05-29 20:44 UTC, MattPereira commented on packages/foundry/test/Multisend.t.sol
> +    address payable zoro;
![one-piece](https://github.com/BuidlGuidl/eth-tech-tree-challenges/assets/73561520/f9c3bb7d-a0db-4b3b-9c40-aeefe7711b5f)

2024-05-30 20:46 UTC, escottalexander requested changes
Looking good. Left some feedback. Mostly just stuff we had discussed before. The way you have defined the functions looks good to me.

2024-05-30 20:46 UTC, escottalexander commented on packages/foundry/script/Deploy.s.sol
You should also deploy your test token here so that users that want to use the front end debug tab will have a token to work with.

2024-05-30 20:46 UTC, escottalexander commented on README.md
As we discussed, no need to add lengthy instructions in the readme. Let's add it to the NatSpec instead.

2024-05-30 20:46 UTC, escottalexander commented on packages/foundry/contracts/Multisend.sol
> +    event SuccessfulETHTransfer(address indexed _sender, address[] indexed _receivers, uint256[]  _amounts);
This is being really picky but calling it "Successful..." is sorta redundant. Consider changing to "ETHTransfer" and "TokenTransfer" unless you feel strongly.

2024-05-30 20:46 UTC, escottalexander commented on packages/foundry/contracts/Multisend.sol
> +    error Multisend__ParamArraysNotEqualLength(uint256 _recipientArrayLength, uint256 _amountsArrayLength);
Why is this error separated from the rest?

2024-05-30 20:46 UTC, escottalexander commented on packages/foundry/contracts/Multisend.sol
The way you are transferring ETH and tokens looks good.

2024-05-30 22:35 UTC, steve0xp commented on packages/foundry/script/Deploy.s.sol
I think I got it with the last commit, but lmk if you'd prefer something else.

2024-05-30 22:35 UTC, steve0xp commented on packages/foundry/contracts/Multisend.sol
> +    error Multisend__ParamArraysNotEqualLength(uint256 _recipientArrayLength, uint256 _amountsArrayLength);
Simply forgot to move it with the rest. I've moved it now.

2024-05-30 22:35 UTC, steve0xp commented on packages/foundry/contracts/Multisend.sol
> +    event SuccessfulETHTransfer(address indexed _sender, address[] indexed _receivers, uint256[]  _amounts);
I'm all good with your change request.

2024-05-30 22:37 UTC, steve0xp commented on README.md
Yep, that's the last thing on my TODO list for this. Add requirements notes to the natspec and clean-up README.

2024-05-31 15:13 UTC, steve0xp commented
@escottalexander I've made the change requests you've asked for, and updated the README and added Requirements into the two main functions of the challenge. Let me know if there is anything else you'd like adjusted. Otherwise I'll merge this to the main repo once you approve it :)

2024-05-31 17:28 UTC, escottalexander requested changes
Your readme revisions look great! Just a couple small things I noticed.

2024-05-31 17:28 UTC, escottalexander commented on packages/foundry/contracts/Multisend.sol
>              require(success, "Transfer failed.");
We should have a custom function and test for this case. Look at my recent PR for the token-wrapper challenge to see a test case that does this. Or maybe you know a better way to test it.

2024-05-31 17:28 UTC, escottalexander commented on packages/foundry/test/Multisend.t.sol
>          // zoro sends dai and weth
This comment should be "zoro sends ETH"

2024-05-31 18:09 UTC, swellander reviewed
:crossed_swords: Crushing it :pirate_flag:

2024-05-31 18:09 UTC, swellander commented on README.md
> +ETH and token transferrance are used all the time within the web3 space. Anyone can see it when they follow txs with NFTs, DeFi, RWAs, gaming, and more. As we can see in other challenges in this repo
spelling of `transference` here

2024-05-31 18:09 UTC, swellander commented on packages/foundry/test/Multisend.t.sol
> +        vm.startPrank(nami);
This is super minor and feel free to leave as is, but it looks like `vm.prank()` only affects the next call, so I think we could get away with just a `vm.prank(nami)` instead of book-ending with `vm.startPrank` and `vm.stopPrank` in a few places

2024-05-31 18:10 UTC, steve0xp commented on packages/foundry/contracts/Multisend.sol
>              require(success, "Transfer failed.");
Hmm. Okay, imo if it failed this it would be shown that it was something with the actual eth transfer. But I get it, you'd like it to be explicit here.

I'll use an error called: `error Multisend__ETHTransferFailed` for this.

2024-05-31 18:56 UTC, steve0xp commented on packages/foundry/contracts/Multisend.sol
>              require(success, "Transfer failed.");
Okay we figured this out in a side chat.

2024-05-31 18:58 UTC, steve0xp commented on README.md
> +ETH and token transferrance are used all the time within the web3 space. Anyone can see it when they follow txs with NFTs, DeFi, RWAs, gaming, and more. As we can see in other challenges in this repo
Corrected

2024-05-31 19:00 UTC, steve0xp commented on packages/foundry/test/Multisend.t.sol
> +        vm.startPrank(nami);
Good catch, made the changes :)

2024-05-31 19:01 UTC, steve0xp commented
@escottalexander @swellander thanks for your PR reviews. I've made the additional changes you've outlined. :)

2024-05-31 19:32 UTC, swellander approved these changes
:fire:

2024-05-31 20:22 UTC, escottalexander approved these changes
Nice work!

2024-05-31 20:33 UTC, merged