Moloch rage quit
BuidlGuidl/eth-tech-tree-challenges-old pull request #32
Opened 2024-05-30 13:40 UTC by KcPele

## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

2024-06-01 12:49 UTC, escottalexander requested changes
Gave it an initial check over. I outlined a few things that need to change but you are headed in the right direction overall.

2024-06-01 12:49 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    function addMember(address newMember) external onlyOwner {
The DAO should get to decide if a member is added or removed. Anyone should be able to call these methods as long as a proposal to add/remove a member has been passed.

2024-06-01 12:49 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    function withdraw(uint256 amount) public onlyOwner {
I don't think this function has a purpose. The DAO is collectively owned so there is no single owner. You can remove the Ownable import as well.

2024-06-01 12:49 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    function withdraw(uint256 amount) public onlyOwner {
You can add a method that executes calldata defined in a proposal. This will be how the DAO's balance changes. When the DAO votes to send funds somewhere and it is approved, anyone can call the method to send those funds.

2024-06-01 12:49 UTC, escottalexander commented on packages/foundry/contracts/MaliciousContract.sol
Curious what you had in mind for this. It is out of scope for the challenge but pretty cool that you were thinking about this attack vector. We will probably utilizing reentrancy in our tests for most challenges in the future but this may be a little premature.

2024-06-01 12:49 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    function rageQuit() external onlyMember {
This looks great!

2024-06-04 15:55 UTC, escottalexander requested changes
I have some bigger thoughts for you that will require larger changes.

2024-06-04 15:55 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
I am rethinking this.
1. Let's make the propose method accept a `contractAddr`, `data` and `value` param (see #33 for an example of this) and remove `ethAmount` and `shareAmount` from the struct. Also add a `deadline` param so that there is a time window for voting.
2. Add a new method called `executeProposal` or similar. Anyone can call it but it will check that the proposal has been approved and the proposal deadline is over. If true then it executes the data with the value. This way the method can be used to execute any transaction (not just approving members). If the proposal is rejected then it should refund any value that was deposited when the proposal was made.
3. Change the `addMember` method to have a modifier that only allows it to be called as the result of a proposal being executed (maybe `msg.sender == address(this)`?). `addMember` should accept all the params needed to give shares to the proposed new member.
4. `removeMember` should be very similar to add `addMember` but perform the opposite logic.

As you think through it you may find you have to add/remove other methods and logic that I haven't thought of yet.

2024-06-04 16:13 UTC, KcPele commented
Great review

On Tue, 4 Jun 2024, 16:55 escottalexander, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I have some bigger thoughts for you that will require larger changes.
> ------------------------------
>
> On packages/foundry/contracts/MolochRageQuit.sol
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/32#discussion_r1626256823>
> :
>
> I am rethinking this.
>
>    1. Let's make the propose method accept a contractAddr, data and value
>    param (see #33
>    <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/33> for
>    an example of this) and remove ethAmount and shareAmount from the
>    struct. Also add a deadline param so that there is a time window for
>    voting.
>    2. Add a new method called executeProposal or similar. Anyone can call
>    it but it will check that the proposal has been approved and the proposal
>    deadline is over. If true then it executes the data with the value. This
>    way the method can be used to execute any transaction (not just approving
>    members). If the proposal is rejected then it should refund any value that
>    was deposited when the proposal was made.
>    3. Change the addMember method to have a modifier that only allows it
>    to be called as the result of a proposal being executed (maybe msg.sender
>    == address(this)?). addMember should accept all the params needed to
>    give shares to the proposed new member.
>    4. removeMember should be very similar to add addMember but perform
>    the opposite logic.
>
> As you think through it you may find you have to add/remove other methods
> and logic that I haven't thought of yet.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/32#pullrequestreview-2096813495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APJDTO4LVNSS3G6T4RBJJ4LZFXPQXAVCNFSM6AAAAABIQ6UQJOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOJWHAYTGNBZGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-09 15:43 UTC, KcPele commented on packages/foundry/contracts/MolochRageQuit.sol
i have updated it.

2024-07-09 15:48 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
Is there a reason why it is still a draft PR? I generally think of draft PRs as PRs that aren't ready for review.

2024-07-09 16:53 UTC, KcPele commented
@escottalexander, I  want to get your feedback before I completely write out the test

2024-07-09 18:32 UTC, escottalexander requested changes
Nice job on this. This is exactly what I had in mind. I made a few comments to further refine.

2024-07-09 18:32 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    ) external onlyMember {
Do we only want members to be able to propose? Seems like we also want non-members to propose to add themselves as members.

2024-07-09 18:32 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +            revert MolochRageQuit__ProposalNotApproved();
This will always trigger a revert if the proposal is not approved which means the proposer can never be refunded. Maybe you meant to emit an event here instead?

2024-07-09 18:32 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +            revert MolochRageQuit__FailedTransfer();
Maybe we need a new revert message that is failure to execute instead of failed transfer as that may not make sense if no value was being transferred.

2024-07-09 18:32 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +        (bool success, ) = proposal.contractAddr.call{value: proposal.value}(
We should not send any value if the `proposal.contractAddr == address(this)` because the value doesn't need to move anywhere, it is already in the contract.

2024-07-09 18:32 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
>      function exchangeShares(uint256 proposalId) external payable onlyMember {
Instead of onlyMember we should use onlyContractAddress on this method.

2024-07-09 18:32 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
>      function exchangeShares(uint256 proposalId) external payable onlyMember {
It also shouldn't be external or payable. No value needs to move to use the function when executing a proposal.

2024-07-09 18:32 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
>      function exchangeShares(uint256 proposalId) external payable onlyMember {
Also addMember's logic should be called  in this method OR we should define another method that handles calling both. We want a single proposal to be able to do both actions and the exchanging shares is part of becoming a member so no reason to separate them.

2024-07-09 20:56 UTC, KcPele commented on packages/foundry/contracts/MolochRageQuit.sol
>      function exchangeShares(uint256 proposalId) external payable onlyMember {
for  exchangeShares, it deals with msg.value that why it is payable and users send funds to the smart contract. if am to call exchangeShares in addMembers then I should also call rageQuit in remove member

```sol
function __exchangeShares(
        uint256 proposalId
    ) private payable onlyContractAddress {
        Proposal storage proposal = proposals[proposalId];
        if (proposal.proposer != msg.sender || !proposal.approved) {
            revert MolochRageQuit__ProposalNotApproved();
        }
        if (msg.value < proposal.value) {
            revert MolochRageQuit__InsufficientETH();
        }

        totalEth += msg.value;
        totalShares += proposal.value;
        shares[msg.sender] += proposal.value;

        emit SharesExchanged(msg.sender, msg.value, proposal.value);
    }
  function addMember(address newMember) external onlyContractAddress {
        if (members[newMember]) {
            revert MolochRageQuit__MemberExists();
        }
__exchangeShares()
        members[newMember] = true;
        emit MemberAdded(newMember);
    }


 function __rageQuit() private onlyContractAddress {}
  function removeMember(address member) external onlyContractAddress {
__rageQuite()
        members[member] = false;
        emit MemberRemoved(member);
    }
'''

2024-07-11 08:26 UTC, KcPele commented
@escottalexander i have effected the changes

2024-07-18 12:20 UTC, escottalexander requested changes
Left a few small comments. Getting really close with this one.

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +////////////////////
Add a space above this line.

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    ///////////////////
Add a space above this line

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    ///////////////////
Add a space above this line

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +     * - `contractAddr` should not be zero address.
We should tell the challenger what error to revert with in each of these cases.

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +     * - The proposal must be approved.
Tell the challenger what to revert with for each of these cases

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +     * - The caller must have shares and must be a member.
Tell them what to revert with if it doesn't match this case

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    function __rageQuit(address member) private onlyContractAddress {
This can be called by any member. Not just the contract as the result of a proposal. Change the modifier.

2024-07-18 12:20 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    }
It doesn't appear that the member is removed. I would expect `removeMember` to be called.

2024-07-18 13:35 UTC, KcPele commented on packages/foundry/contracts/MolochRageQuit.sol
> +    }
i made rageQuit handle everything

2024-07-19 14:42 UTC, escottalexander commented
@KcPele Can you resolve the merge conflicts please?

2024-07-19 17:39 UTC, escottalexander requested changes
Gave this a deeper look and found some issues that need to be sorted through.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +     * - Only callable by the contract itself. User onlyContractAddress to be sure only the contract can call the function.
~~User~~ Use

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +        uint256 proposalId
The proposalId is unnecessary. Any member should be able to rageQuit without referencing a proposal.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +        address member,
Rage Quit should only be called by the member who is rage quitting so no need to accept a `member` param. Just use `msg.sender`.

__RageQuit is only callable by a member who wants to be done being a member and wants to cash out. Nobody should be able to call it on behalf of another member.__

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +error MolochRageQuit__InsufficientShares();
`MolochRageQuit__InsufficientShares` is unused

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +error MolochRageQuit__NotEnoughVotes();
`MolochRageQuit__NotEnoughVotes` is unused.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +////////////////////
These errors should be defined inside the contract. I realize the layout guidelines are confusing as it lists contracts below errors but what this means is contracts variables defined inside the contract.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +        uint256 value,
No need for this to be a parameter. We should just use `msg.value`.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    uint256 public totalEth;
totalEth doesn't need to be defined or tracked in any way. You can get the contract balance with address(this).balance

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +error MolochRageQuit__NotAMamber();
~~NotAMamber~~ NotAMember

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    uint256 public quorum;
The way quorum is used is somewhat flawed. It should probably be replaced with a memberCount and then a formula is used to make sure a majority has voted. It should never allow one person to be the sole decider of a vote unless there is only one member.

In your current setup the only place they can set the quorum is in the constructor which it could never be set to more than 1 or else there would be no way to add a second member. If the quorum remains one indefinitely then one vote decides the outcomes for any proposal to no matter how many members there are. Yikes.

Perhaps there should be a minimum quorum of voters (maybe as low as 5%) that is required for a proposal to be approved but there is a more robust yea vs nay formula used after the deadline has passed. Because maybe only 10% of members voted and maybe that minimum quorum was reached but there were more nay votes than yea votes. I don't want to over complicate the contract so I am open to your ideas but the current mechanism is broken.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +        proposal.votes++;
In regards to my suggestions for updating the `quorum` variable: Maybe the proposal should track yea votes and nay votes instead of just votes in general.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +            emit ProposalApproved(proposalId, msg.sender);
I don't think it makes sense for a proposal to be approved before the voting period is over. More nay votes might counteract the current approval. The approval/denial should be decided in the `executeProposal function`. That is the only place where it being approved/denied matters.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    function executeProposal(
This function is overly complicated. It might help the user to instead have a `executeApprovedProposal` function and a `refundDeniedProposal` function. Each function could check if Yea > Nay or the opposite before executing.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +            proposal.approved = true;
Remove `approved` on the proposal and instead track yea votes and nay votes. Approval depends on the proposal deadline being reached, total votes > quorum, and proposal.yeaVotes > proposal.nayVotes

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    modifier onlyMember(address _member) {
It seems that the onlyMember modifier could be simplified to use msg.sender inside the modifier instead of accepting it as a param.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +    function executeProposal(
There is nothing to keep me from executing a proposal multiple times. Yikes! Make sure you set the new  property before `call`ing external contracts because this is a reentrancy risk. Would be great to add tests around this too.

2024-07-19 17:39 UTC, escottalexander commented on packages/foundry/contracts/MolochRageQuit.sol
> +        if (members[newMember]) {
This check is the only thing keeping someone from executing the proposal multiple times. But what if I get in at a low share price and Rage Quit at a high share price? Then I can become a member again at my low share price by reexecuting my old proposal! I could do this over and over until the contract was drained.

2024-11-09 22:02 UTC, escottalexander commented
We changed the format of the challenge and added it to a new repo. I based the new branch off of your changes. Thanks for your contribution! https://github.com/BuidlGuidl/eth-tech-tree-challenges/tree/moloch-rage-quit

2024-11-09 22:02 UTC, closed without merging