Social Recovery Wallet Challenge
BuidlGuidl/eth-tech-tree-challenges-old pull request #33
Opened 2024-05-30 19:44 UTC by swellander

Closes #23 

## Description
Creates the Social Recovery Wallet Challenge.

### Some potential extra credit features 
- Ability to add/remove guardians
- Hide identity of guardians
- Add expected wallet functionality (send/receive tokens, call other contracts, etc.)

2024-05-30 20:25 UTC, escottalexander commented
> @escottalexander I think you'll need to create a `social-recovery` branch to merge this into

I just created the new branch. You can point this PR to that one now instead of main.

2024-05-30 22:30 UTC, swellander commented
> I just created the new branch. You can point this PR to that one now instead of main.

Done

2024-05-31 16:52 UTC, escottalexander requested changes
Looking good, Sam. Left a few suggestions.

2024-05-31 16:52 UTC, escottalexander commented on README.md
> +Mother's day, 2023. You decide to send your mom some ETH to help her learn more about your world. You set up a new MetaMask wallet and write down the seed phrase on a nice peice of flowered stationar
~~extatic~~ ecstatic

2024-05-31 16:52 UTC, escottalexander commented on README.md
> +Mother's day, 2023. You decide to send your mom some ETH to help her learn more about your world. You set up a new MetaMask wallet and write down the seed phrase on a nice peice of flowered stationar
Great story setup BTW. :smile:

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> + * @dev This smart contract is PURELY EDUCATIONAL, and is not to be used in production code. It is up to the user's discretion to make their own production code, run tests, have audits, etc.
Haha good idea to have a disclaimer.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> + * @dev This smart contract is PURELY EDUCATIONAL, and is not to be used in production code. It is up to the user's discretion to make their own production code, run tests, have audits, etc.
~~I would mention in the readme or here that for our purposes the wallet can only send/receive ETH. It is not a fully functioning smart contract wallet.~~ I think it is fairly easy to add full functionality to this wallet. Details on the sendETH method.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +     * @param _value: The amount of ETH you're sending, if any
For each of these functions, lets provide a requirements section. look here for what it should be like: https://github.com/MattPereira/eth-tech-tree-challenges/blob/eth-and-token-streaming/packages/foundry/contracts/EthStreaming.sol

We want to give the users enough instruction to know what is expected from the function but without giving the exact instructions on how to do it.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +        require(success, "external call reverted");
Should use a custom error instead of this because a user could make this string anything but they will have clarity if there is a "CallFailed" error that we mention in the requirements.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function sendEth(address _callee, uint256 _value) external onlyOwner notBeingRecovered returns (bytes memory) {
Instead of "sendETH" what if this becomes "call" and we accept bytes calldata that we then send to the callee?
```solidity
   function call(address _callee, uint256 _value, bytes calldata _data) external onlyOwner notBeingRecovered returns (bytes memory) {
        (bool success, bytes memory result) = _callee.call{value: _value}(_data);
        require(success, "external call reverted");
        return result;
    }
```

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function sendEth(address _callee, uint256 _value) external onlyOwner notBeingRecovered returns (bytes memory) {
We could also add some tests that check for this calldata forwarding behavior. You could test with anything but an easy way would be to send some ERC20s to the contract and use this method to send them somewhere.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function sendEth(address _callee, uint256 _value) external onlyOwner notBeingRecovered returns (bytes memory) {
Let me know if you need any help figuring it out.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function initiateRecovery(address _proposedOwner) onlyGuardian notBeingRecovered external {
move `external` to be the first thing declared like in your above function.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function supportRecovery(address _proposedOwner) onlyGuardian isBeingRecovered external {
move `external` to be the first thing declared like in your above function.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +        for (uint i = 0; i < _guardians.length; i++) {
This is fine to add guardians in the constructor but I think that in addition to this we should ahve addGuardian and removeGuardian methods that the owner can call. This makes it easier to test from a front end without modifying the deploy script.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +        for (uint i = 0; i < _guardians.length; i++) {
Should probably add methods for changing the threshold too.

2024-05-31 16:52 UTC, escottalexander commented on packages/foundry/script/Deploy.s.sol
> +    address[] chosenGuardianList = [guardian0, guardian1, guardian2];
I would remove these from the deploy script since the end user won't have access to these accounts.

2024-05-31 17:20 UTC, swellander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> + * @dev This smart contract is PURELY EDUCATIONAL, and is not to be used in production code. It is up to the user's discretion to make their own production code, run tests, have audits, etc.
I took this from @steve0xp's PR :pray:

2024-05-31 17:27 UTC, swellander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function sendEth(address _callee, uint256 _value) external onlyOwner notBeingRecovered returns (bytes memory) {
I originally had this as `sendArbitraryTx()`, accepting a `_data` param, but then decided to limit it to just sending ETH to keep the focus on the social recovery. I will change it back, though. I agree that it's pretty standard behavior that should be included

2024-05-31 17:32 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function sendEth(address _callee, uint256 _value) external onlyOwner notBeingRecovered returns (bytes memory) {
Props for thinking about keeping the main lesson in view. That was smart. These are meant to be intermediate - advanced challenges though so I think they can handle it.

2024-06-02 21:54 UTC, swellander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +    function supportRecovery(address _proposedOwner) onlyGuardian isBeingRecovered external {
good catch!

2024-06-03 18:30 UTC, swellander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +        for (uint i = 0; i < _guardians.length; i++) {
Good call :+1:

2024-06-03 18:32 UTC, swellander commented
@escottalexander thanks for the review! I believe I've addressed all your comments

2024-06-04 14:33 UTC, escottalexander requested changes
Looking really great! Just a few very small items to check over.

2024-06-04 14:33 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +        if (_threshold > numGuardians) {
Great idea to check this. You should add the error in the requirements.

2024-06-04 14:33 UTC, escottalexander commented on packages/foundry/test/SocialRecoveryWallet.t.sol
> +    function testCallCanExecuteExternalTransactions() public {
Perfect!

2024-06-04 14:33 UTC, escottalexander commented on packages/foundry/test/SocialRecoveryWallet.t.sol
> +    function testAddGuardian() public {
I think we should also check that the guardians count is adjusted here, right?

2024-06-04 14:33 UTC, escottalexander commented on packages/foundry/test/SocialRecoveryWallet.t.sol
> +    function testRemoveGuardian() public {
I think we should also check that the guardians count is adjusted here, right?

2024-06-04 14:33 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +     */
I don't want to give too many instructions to the challenger but do you think we should mention the numGuardians adjustment?

2024-06-04 14:33 UTC, escottalexander commented on packages/foundry/contracts/SocialRecoveryWallet.sol
> +     */
I don't want to give too many instructions to the challenger but do you think we should mention the numGuardians adjustment?

2024-06-05 19:02 UTC, swellander commented on packages/foundry/test/SocialRecoveryWallet.t.sol
> +    function testRemoveGuardian() public {
Good catch!

2024-06-05 19:03 UTC, swellander commented
@escottalexander thanks for taking the time for the further review! I made all the changes you commented about

2024-06-17 20:27 UTC, escottalexander approved these changes
This is perfect. Great work!

2024-06-17 20:28 UTC, merged