Write Initial Rebasing Token Educational Challenge & Tests
BuidlGuidl/eth-tech-tree-challenges-old pull request #35
Opened 2024-05-31 17:58 UTC by steve0xp

## Description

Create Rebasing Token Challenge as per issue #5.

## TODO

- [x] Create initial `RebasingERC20.sol`
- [x] Create initial `RebasingERC20.t.sol` tests (pseudo-code)
- [x] Debug tests and contract to ensure challenge works
- [ ] Add Event and Error tests
- [ ] Write README sections

## Related Issues

_Closes #5_

Your ENS/address: steve0xp.eth

2024-06-01 11:51 UTC, escottalexander requested changes
I like your approach. Left a couple comments for you to ponder.

2024-06-01 11:51 UTC, escottalexander commented on packages/foundry/contracts/RebasingERC20.sol
> +        if(epoch == 0) revert RebasingERC20__BadEpoch(epoch);
Help me understand the purpose of designating an epoch. Couldn't I do several sequential rebase events with the same epoch number? I feel like it will be confusing for users to understand why they need to implement it. Maybe you are thinking about something I don't see yet but would it hurt to just remove the concept entirely?

2024-06-01 11:51 UTC, escottalexander commented on packages/foundry/contracts/RebasingERC20.sol
> +        return _balances[account] * _scalingFactor / (1e18);
How can we handle rounding errors in a clean way? It would be nice to give the end user instructions that either completely avoid rounding errors by way of requiring a coding solution that handles them well or by letting them know (and enforcing) that rebase events only move by specific quantities.

Take the following test for example: 
```solidity
function testFuzzRebasePositive(int256 supplyAdjustment) public {
        vm.assume(supplyAdjustment > 1);
        vm.assume(supplyAdjustment % int256(10 ** 6) == 0);
        uint256 epoch = 1;
        int256 supplyDelta = supplyAdjustment;
        uint256 oldTotalSupply = token.totalSupply();
        uint256 expectedTotalSupply = uint256(int256(oldTotalSupply) + supplyAdjustment);
        
        vm.expectEmit(true, false, false, true);
        emit Rebase(epoch, expectedTotalSupply);
        token.rebase(epoch, supplyDelta);
        uint256 newTotalSupply = token.totalSupply();

        assertEq(newTotalSupply, oldTotalSupply + uint256(supplyDelta));
        assertEq(token.balanceOf(luffy), luffyBalance1* (newTotalSupply) / oldTotalSupply);
        assertEq(token.balanceOf(zoro), (zoroBalance1 * newTotalSupply) / oldTotalSupply);
    }
```
The modulo 'assume' guarantees rounding errors won't happen because of the largeness and whole-divisibility of the number. In the end we can handle it however you like but I think we should be explicit in our requirements.

2024-06-03 12:53 UTC, steve0xp commented on packages/foundry/contracts/RebasingERC20.sol
> +        if(epoch == 0) revert RebasingERC20__BadEpoch(epoch);
I was going off the idea that rebasing tokens, from my memory (which could be wrong), had epochs involved. I forgot to increment and add epochs as storage value to the contract.

That said, I think for the purpose of this challenge, which is just to showcase rebasing as a general concept, we should remove `epochs`. Thanks for asking about this!

2024-06-25 19:38 UTC, steve0xp commented on packages/foundry/contracts/RebasingERC20.sol
> +        return _balances[account] * _scalingFactor / (1e18);
This is a good point. Upon quick reflection, I am leaning towards adding in requirements that the rebasing adjustment can only be up to a certain amount, and must have whole-divisibility. 

For our case, the rebase adjusts the total supply. At the start the total supply = the initial supply = 1 million tokens. I propose having the rebase amount not exceed something like `25e3` (aka 2.5% of initial supply). We also can have the modulo in place as a requirement within the implementation logic to further remove rounding error chances.

Since we're dealing with just one mathematical operation at most, I'd think that this should take care of the rounding errors you're presenting. Obv avoiding multiple mathematical operations is very important.

2024-06-27 15:35 UTC, steve0xp commented
## Update Since Last Submission

- Created most of the tests for the challenge
- Researched, Iterated (upon feedback and research) on challenge scope, Redesigned challenge code
- Updated README
- Now submitting this for first PR Review to get more detailed feedback on direction, implementation, and thoughts on remaining tests (specifically how to go about the rounding error test(s)).

## Remaining Work

- [ ] Resolve PR CRs once @escottalexander has a chance to provide a PR review.
   - [ ] Finish off remaining tests (rounding error test, and transferAllFrom after rebase test)
   - [ ] Update README to align with code challenge nat spec for rounding errors

2024-07-01 16:18 UTC, escottalexander requested changes
Left some comments for you to consider. I think this is going a good direction. Really close now.

2024-07-01 16:18 UTC, escottalexander commented on README.md
> +This challenge will require users to write an ERC20 contract that contains rebasing token logic such that when a event occurs.
This sentence needs reworking. Seems like there need to be more added to the end.

2024-07-01 16:18 UTC, escottalexander commented on packages/foundry/contracts/RebasingERC20.sol
> +    function transferAllFrom(address from, address to) external returns (bool) {
Seems odd that this requires a separate function. Why can't I use tranferFrom and get the same results?

2024-07-01 16:18 UTC, escottalexander commented on packages/foundry/contracts/RebasingERC20.sol
> +        // _burn(msg.sender, amount);
I assume this is being revisited?

2024-07-01 16:18 UTC, escottalexander commented on packages/foundry/test/RebasingERC20.t.sol
> +        token = new RebasingERC20(); // TODO - check logs to see if it is calling mint or not on the RBT! If it is, then keep the mint logic within the transfer stuff. If it isn't, then you can remov
Good idea to check this.

2024-07-01 16:18 UTC, escottalexander commented on packages/foundry/test/RebasingERC20.t.sol
> +     */
As I think about it, I think maybe you are overthinking it. You should have some solid fuzz tests that provides 'uint transferAmount'. Then check that the transfer amount is as expected, then rebase, then check that the balanceOf is as expected based on a recreation of your rebase logic. The real test is just making sure your logic holds up with any user balance. I think everything else is already covered by your other tests.

2024-07-01 16:18 UTC, escottalexander commented on packages/foundry/test/RebasingERC20.t.sol
> +    // function testTransferAllFromAfterRebase(uint256 transferAmount) public {
Again, I have no idea why we need a special new function for transferring all tokens. normal transfer functions should handle this.

2024-07-02 18:49 UTC, steve0xp commented on packages/foundry/contracts/RebasingERC20.sol
> +    function transferAllFrom(address from, address to) external returns (bool) {
Yes, good point. I wasn't really focusing on this, but I agree that we just need to validate that transferring more than a user has it impossible in tests. Then `transferFrom` can just handle transferring all tokens from an address

2024-07-02 19:35 UTC, steve0xp commented on packages/foundry/test/RebasingERC20.t.sol
> +        token = new RebasingERC20(); // TODO - check logs to see if it is calling mint or not on the RBT! If it is, then keep the mint logic within the transfer stuff. If it isn't, then you can remov
Removing the `mint` conditional logic after checking logs.

2024-07-02 19:40 UTC, steve0xp commented on packages/foundry/test/RebasingERC20.t.sol
> +     */
Thanks for your thoughts on this. Based on your review then, I think that the following tests already cover what you are discussing: `testTransferFromAfterRebase` and `testTransferAfterRebase`.

Let me know if that suffices. I will remove this commented out test and TODOs.

2024-07-02 19:49 UTC, steve0xp commented on packages/foundry/contracts/RebasingERC20.sol
> +        // _burn(msg.sender, amount);
I had commented it out as I thought it needed to be revisited, but the burn logic is handled within the `_beforeTokenTransfer()` logic.

2024-07-02 19:50 UTC, steve0xp commented on packages/foundry/test/RebasingERC20.t.sol
> +    // function testTransferAllFromAfterRebase(uint256 transferAmount) public {
Yep, I acknowledged this in your other comment. This function and its tests have been removed. I have added tests to check that the other transfer functions transfer total balances of a user properly.

2024-07-02 20:14 UTC, steve0xp commented on README.md
> +This challenge will require users to write an ERC20 contract that contains rebasing token logic such that when a event occurs.
Edited, thanks!

2024-07-02 20:15 UTC, steve0xp commented
@escottalexander thanks for your reviews! I've responded to your comments and made changes to the code accordingly. It should be ready to review again and hopefully we can merge it to the repo soon :)

2024-07-03 13:25 UTC, escottalexander requested changes
Couple very small items and then this is good to go. Nice work!

2024-07-03 13:25 UTC, escottalexander commented on packages/foundry/contracts/RebasingERC20.sol
Super nitpicky but can we update the headers for each section to have this appearance as they do in all our other challenges?
```
    ///////////////////
    // Public Functions
    //////////////////   
```

2024-07-03 13:25 UTC, escottalexander commented on packages/foundry/contracts/RebasingERC20.sol
>      /// Helper Functions (not part of the challenge)
Not sure what this comment is doing here. Seems like the functions that follow it are part of the challenge.

2024-07-03 13:25 UTC, escottalexander commented on README.md
Still need to change the first few lines of this to match the feel of past challenges. I almost missed it too.

2024-07-03 13:25 UTC, escottalexander commented on README.md
>  Feel free to ask any questions or express any ideas that will help the end user learn through this challenge.
This line and the one below it are leftover from the instructions for writing the challenge. Scan thoroughly to make sure I didn't miss any other lines.

2024-07-03 13:25 UTC, escottalexander commented on README.md
>  Feel free to ask any questions or express any ideas that will help the end user learn through this challenge.
Also `*--End of challenge specific section--*` can be removed.

2024-07-03 17:53 UTC, steve0xp commented on packages/foundry/contracts/RebasingERC20.sol
I've made the changes, thanks for pointing it out!

2024-07-03 17:54 UTC, steve0xp commented on packages/foundry/contracts/RebasingERC20.sol
>      /// Helper Functions (not part of the challenge)
It was more for my organization before. I've removed it for the challenge. The `abs()` helper function will have its implementation kept in the challenge, but the student is to go through the challenge and make the `_beforeTokenTransfer()` implementation.

2024-07-03 17:57 UTC, steve0xp commented on README.md
>  Feel free to ask any questions or express any ideas that will help the end user learn through this challenge.
Good catch, I couldn't remember what was needed to be kept from that template markdown content. I've removed them accordingly.

2024-07-03 18:06 UTC, steve0xp commented on README.md
Sounds good, I've made an intro. BTW the example challenge doesn't have an intro [here](https://github.com/BuidlGuidl/eth-tech-tree-challenges/blob/token-wrapper-weth/README.md). I was looking at it for reference on how to make the branch after your most recent PR review and just noticed it.

2024-07-03 18:12 UTC, steve0xp commented
@escottalexander changes have been made. Thanks again for all of your help and these reviews!

2024-07-03 19:08 UTC, escottalexander commented on README.md
Thanks for pointing that out. I made a new issue for that.

2024-07-03 19:10 UTC, escottalexander approved these changes
Looks good!

2024-07-03 19:11 UTC, merged