Dao governance proposals and voting
BuidlGuidl/eth-tech-tree-challenges-old pull request #37
Opened 2024-05-31 23:41 UTC by blahkheart

## Description

Dao governance proposals and voting challenge

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #25

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: dannithomx.eth

2024-06-01 12:31 UTC, escottalexander requested changes
I like your implementation. Left a few suggestions and a larger request for some styling adjustments. This is getting close. Thanks for your hard work!

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/contracts/Governance.sol
The Token Voting challenge that you based this on was completed before we had this style guide and custom error requirements. Can you update your challenge to use the new styling and custom errors (testing the custom errors will need to be added as well)?

Details here:
```
// Layout of Contract:
// version
// imports
// errors
// interfaces, libraries, contracts
// Type declarations
// State variables
// Events
// Modifiers
// Functions

// Layout of Functions:
// constructor
// receive function (if exists)
// fallback function (if exists)
// external
// public
// internal
// private
// internal & private view & pure functions
// external & public view & pure functions
```
Let's also designate the different sections with large block comments like this:
```
    ///////////////////
    // Public Functions
    ///////////////////
```

Lastly, let's use custom errors. For several contracts we have been doing generic reverts with strings but in the tests we can only expect *any* revert. By using custom errors and informing challengers about them in the requirements we are able to test that a contract reverts for a specific reason. This is also generally better practice for gas efficiency.

Look at several of the more recent completed challenges to get an idea.

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/contracts/Governance.sol
> +    * @param _votingPeriod The duration of the voting period in seconds
Need to add a 'requirements' section to each of these so that when we remove the code inside the function, the challenger has an idea about what the function needs to do. Look at the Token Wrapper challenge or others for ideas about what that looks like.

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/test/Governance.t.sol
> +        governance.vote(proposalId, Choice.NAY);
How is this a tie if Nay has two votes and Yea only has one? I would expect this test to have an equal amount of yeas and nays and the result to be false (as you have it).

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/test/Governance.t.sol
> +        governance.propose("Failing Proposal");
When you have added custom errors each of these 'Fail' tests should be checking for the exact custom error to be thrown.

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/test/Governance.t.sol
> +    function testVotingResultRejected() public {
OH, I think the body of this test and the above one needs to be swapped. Just a naming mistake.

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/test/Governance.t.sol
> +        governance.vote(proposalId, Choice.NAY);
See comment on testVotingResultRejected.

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/contracts/Governance.sol
> +    function getProposal(bytes32 _proposalId) external view returns (Proposal memory) {
I think you can remove this function and just get the values of the proposal directly in the test.

2024-06-01 12:31 UTC, escottalexander commented on packages/foundry/contracts/Governance.sol
> +    function getVotingDeadline(bytes32 _proposalId) public view returns (uint256) {
I think you can remove this function. I t looks like it is unused and you can get it's data from the proposal directly.

2024-06-03 10:41 UTC, blahkheart commented on packages/foundry/test/Governance.t.sol
> +        governance.vote(proposalId, Choice.NAY);
This is a tie because of the number of tokens userThree has (3000) while userOne and userTwo have 1000 and 2000 respectively, therefore both voting Nay, equals 3000 votes for Nay, and userThree voting Yea equals 3000 votes for Yea, hence the tie

2024-06-03 10:45 UTC, blahkheart commented on packages/foundry/test/Governance.t.sol
> +    function testVotingResultRejected() public {
> This is a tie because of the number of tokens userThree has (3000) while userOne and userTwo have 1000 and 2000 respectively, therefore both voting Nay, equals 3000 votes for Nay, and userThree voting Yea equals 3000 votes for Yea, hence the tie

It wasn't a mistake as explained above, since the implementation of the voting outcome from the token voting challenge doesn't include a tie, when a proposal has a tie it defaults to a rejected outcome

2024-06-09 00:45 UTC, escottalexander requested changes
A couple of small issues to look over. Make sure when you are done that you can run the tests.

2024-06-09 00:45 UTC, escottalexander commented on packages/foundry/contracts/Governance.sol
> +/*//////////////////////////////////////////////////////////////
Apparently "/*/////////" type comments aren't allowed in solidity documents. My compiler kept throwing.

Instead of /*////////... Use this:
```
    ///////////////////
    // Errors
    //////////////////
```
Weird that it is ok with natspec but not ok with comment lines like that. shrug

2024-06-09 00:45 UTC, escottalexander commented on packages/foundry/test/Governance.t.sol
> +        assertEq(governance.getProposal(id).title, "New Proposal");
You removed getProposal from the contract so you will need to get the proposal another way.

2024-06-10 13:55 UTC, blahkheart commented on packages/foundry/test/Governance.t.sol
> +        assertEq(governance.getProposal(id).title, "New Proposal");
fixed

2024-06-10 13:56 UTC, blahkheart commented on packages/foundry/contracts/Governance.sol
> +/*//////////////////////////////////////////////////////////////
fixed

2024-06-10 16:26 UTC, escottalexander approved these changes
Looks good. Thanks for your work on this.

2024-06-10 16:26 UTC, merged